### ISSUE TITLE
usr-submission

### ISSUE THREAD

**Issue by moadmmh** [UIACC/codeforces-cli#13]
I'm starting working on this function

**Comment by Sohieb** [comment]
I think this function works just fine. However if you can include when the submission is not accepted, the number of test case where is failed, it would be much better.

Please comment here if you can do that, if so please reopen the issue and start working on it.

**Comment by OmarTahoun** [comment]
Shouldn't this function also return the submission ID, if yes i already did it.

**Comment by OmarTahoun** [comment]
plus there is an issue with the slice function:
it should start from 0 not 1
Example: ```slice(0, count+1)``` not ```slice(1, count+1)```
i also fixed that

**Comment by moadmmh** [comment]
@Sohieeb I'll add it 
@OmarTahoun i already noticed the slice indexing and for the submission id i gss we don't need it we just mentioned that it returns the last n submissions regardless of it's status WA/AC.. but i can add it anyways .

**Comment by OmarTahoun** [comment]
@moadmmh i think we will need it for the flow of the whole program, i just added it anyways, check the master
