### ISSUE TITLE
gen-problems

### ISSUE THREAD

**Issue by AbdoAwad** [UIACC/codeforces-cli#5]
I'm going to start it now ..

**Comment by AbdoAwad** [comment]
The tag should be optional, as a user can get different tags..

**Comment by Sohieb** [comment]
@AbdoAwad It's the same for this https://github.com/UIACC/codeforces-cli/issues/8#issuecomment-466753136

**Comment by AbdoAwad** [comment]
i guess i have done this function, can u check the latest commit

**Comment by Sohieb** [comment]
I tested the function but seems like it generate problems which is already solved by the given user, and none of them was actually of the given tag. something seems not right!!

**Comment by Sohieb** [comment]
Besides, the command always return the same set of problems when run with the same parameters. I think it should give different set each time you execute.

**Comment by AbdoAwad** [comment]
i will check this issue tom.

**Comment by AbdoAwad** [comment]
i solved the problems..

**Comment by Sohieb** [comment]
The problems generated is not guaranteed to be not solved by the given user. I have tried it with (-c 5) and it gave 4 out of the 5 problems as already solved ones.
