### ISSUE TITLE
sub-code

### ISSUE THREAD

**Issue by Sohieb** [UIACC/codeforces-cli#7]
I'm going to take this function.

**Comment by Sohieb** [comment]
@OmarTahoun the commit you did shouldn't close this issue.
I reopened it again until I finish working on it today.

**Comment by OmarTahoun** [comment]
sorry that was my mistake

**Comment by OmarTahoun** [comment]
@Sohieeb Do you need help with this? i have been playing around with it and already got it working on my device

**Comment by OmarTahoun** [comment]
issue is solved for the current version, more features can be added after the refactoring process is done
