### ISSUE TITLE
com-contest

### ISSUE THREAD

**Issue by moadmmh** [UIACC/codeforces-cli#9]
I'm gonna start working on it .

**Comment by Sohieb** [comment]
The command return upcoming and already finished contests, not only upcoming. something seems not to be correct.
Please test the command and modify it to fix this issue and make a new PR.

**Comment by moadmmh** [comment]
Sure

**Comment by moadmmh** [comment]
int this case we don't need a counter we just give back the whole list of the coming and the running contests .
